_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/dino_r50vd_pan.yml',
  '_base_/yoloe_reader.yml',
]

weights: output/dino_r50vd_pan_3_0_6_1x_coco/model_final
find_unused_parameters: True
log_iter: 100


epoch: 12

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 1.0
    milestones: [100]
    use_warmup: true
  - !LinearWarmup
    start_factor: 0.001
    steps: 2000

OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001
