_BASE_: [
  '../runtime.yml',
  '_base_/optimizer_3x.yml',
  '_base_/dino_r50vd_pan.yml',
  '_base_/yoloe_reader.yml',
]

metric: COCO
num_classes: 80
TrainDataset:
  !COCODataSet
    image_dir: JPEGImages/
    anno_path: semi_annotations/trainval.1@5.json
    dataset_dir: dataset/voc
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: JPEGImages/
    anno_path: test.json
    dataset_dir: dataset/voc
    allow_empty: true

TestDataset:
  !ImageFolder
    anno_path: test.json
    dataset_dir: dataset/voc


weights: output/dino_r50vd_pan_4_0_6_3x_voc/model_final
find_unused_parameters: True
log_iter: 100
snapshot_epoch: 10
epoch: 250