_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_5x.yml',
  '_base_/dino_r50vd_pan.yml',
  '_base_/yoloe_reader.yml',
]

weights: output/dino_r50vd_pan_3_0_6_5x_coco/model_final
find_unused_parameters: True
log_iter: 200
snapshot_epoch: 5
# pretrain_weights: http://10.255.134.13:8091/dino/PaddleDetection/output/dino_r50vd_pan_3_0_6_5x_coco/9.pdparams
metric: COCO
num_classes: 20
#before train, change voc to coco with voc2coco.py
# partial labeled COCO, use `SemiCOCODataSet` rather than `COCODataSet`
TrainDataset:
 !COCODataSet
    image_dir: VOC2007/JPEGImages
    anno_path: PseudoAnnotations/VOC2007_trainval.json
    dataset_dir:  dataset/voc/VOCdevkit
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: VOC2007/JPEGImages
    anno_path: PseudoAnnotations/VOC2007_test.json
    dataset_dir:  dataset/voc/VOCdevkit/
    allow_empty: true
