log_iter: 175
snapshot_epoch: 1

for_distill: True


architecture: DETR
pretrain_weights: http://10.181.196.16:8099/weights/distill/best_model_focal_ppdetr_56.4_old.pdparams
norm_type: sync_bn
use_ema: True
ema_decay: 0.9999
ema_decay_type: "exponential"
hidden_dim: 256
use_focal_loss: True

DETR:
  backbone: FocalNet
  neck: HybridEncoder
  transformer: PPDETRTransformer
  detr_head: DINOHead
  post_process: DETRPostProcess

FocalNet:
  arch: 'focalnet_L_384_22k_fl4'
  out_indices: [1, 2, 3]

HybridEncoder:
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1 #1
  encoder_layer:
    name: TransformerLayer
    d_model: 256
    nhead: 8
    dim_feedforward: 1024 #1024
    dropout: 0.
    activation: 'gelu'
  expansion: 1.0

PPDETRTransformer:
  num_queries: 300
  position_embed_type: sine
  feat_strides: [8, 16, 32]
  num_levels: 3
  nhead: 8
  num_decoder_layers: 6
  dim_feedforward: 1024 #1024
  dropout: 0.0
  activation: relu
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0
  learnt_init_query: False

DINOHead:
  loss:
    name: DINOLoss
    loss_coeff: {class: 1, bbox: 5, giou: 2}
    aux_loss: True
    use_vfl: True
    #use_uni_match: True
    #uni_match_ind: 0
    matcher:
      name: HungarianMatcher
      matcher_coeff: {class: 2, bbox: 5, giou: 2}
      # use_pos_only: True


for_distill: True

slim: Distill
slim_method: KDDETR
distill_loss: KDDETRLoss

KDDETRLoss:
  kd_hs: False
  kd_reference: True #False
  kd_enc: True #False
