_BASE_: [
  '../../runtime.yml',
  '../../dino/_base_/optimizer_2x.yml',
  '../../dino/_base_/dino_r50vd_pan.yml',
  '../../dino/_base_/dino_640_reader.yml',
]

#for debug
eval_interval: 3600
save_interval: 3600
weights: output/semi_detr_semi005_size_600_1000/model_final
find_unused_parameters: True
save_dir: output
log_iter: 50
ssod_method: DenseTeacher
### global config
use_simple_ema: True
ema_decay: 0.9996
use_gpu: true

### reader config
worker_num: 4

SemiTrainReader:
  sample_transforms:
    - Decode: {}
    - RandomExpand: {fill_value: [0., 0., 0.]}
    - RandomCrop: {prob: 0.8}
  weak_aug:
    - RandomFlip: {prob: 0.5}
  strong_aug:
    - RandomFlip: {prob: 0.5}
    - StrongAugImage: {transforms: [
        RandomColorJitter: {prob: 0.8, brightness: 0.4, contrast: 0.4, saturation: 0.4, hue: 0.1},
        RandomErasingCrop: {},
        RandomGaussianBlur: {prob: 0.5, sigma: [0.1, 2.0]},
        RandomGrayscale: {prob: 0.2},
      ]}
  sup_batch_transforms:
    - BatchRandomResize: {target_size: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
  unsup_batch_transforms:
    - BatchRandomResize: {target_size: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
  sup_batch_size: 2
  unsup_batch_size: 2
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: false

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 2
  shuffle: false
  drop_last: false


TestReader:
  sample_transforms:
    - Decode: {}
    - Resize: { target_size: [640, 640], keep_ratio: False }
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false


pretrain_student_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams
pretrain_teacher_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams
# pretrain_weights: pp-dino_sup005_390.pdparams
architecture: DETR

hidden_dim: 256
use_focal_loss: True


DETR:
  backbone: ResNet
  neck: YOLOCSPPAN
  transformer: PPDETRTransformer
  detr_head: DINOHead
  post_process: DETRBBoxPostProcess
  post_process_semi: DETRBBoxSemiPostProcess

ResNet:
  # index 0 stands for res2
  depth: 50
  variant: d
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  lr_mult_list: [0.1, 0.1, 0.1, 0.1]
  num_stages: 4
  freeze_stem_only: True

YOLOCSPPAN:
  depthwise: False
  use_trans: True
  nhead: 8
  num_layers: 2
  dim_feedforward: 1024
  dropout: 0.1
  activation: 'gelu'
  proj_dim: [256, 256, 256]
  proj_use_conv: True

PPDETRTransformer:
  num_queries: 300
  position_embed_type: sine
  num_levels: 3
  nhead: 8
  num_decoder_layers: 6
  dim_feedforward: 1024
  dropout: 0.0
  activation: relu
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0
  learnt_init_query: True
  eval_size: [640, 640]

DINOHead:
  loss:
    name: DINOLoss
    loss_coeff: {class: 1, bbox: 5, giou: 2}
    aux_loss: True
    use_vfl: True
    use_same_match: True
    same_match_ind: 0
    matcher:
      name: HungarianMatcher
      matcher_coeff: {class: 2, bbox: 5, giou: 2}
      use_pos_only: True

DETRBBoxPostProcess:
  num_top_queries: 300


SSOD: DETR_SSOD
DETR_SSOD:
  teacher: DETR
  student: DETR
  train_cfg:
    sup_weight: 1.0
    unsup_weight: 1.0
    semi_start_iters: -1
    ema_start_iters:  -1
    #debug
    # semi_start_iters: -1
    # ema_start_iters:  -1
    pseudo_label_initial_score_thr: 0.7
    min_pseduo_box_size: 0
    concat_sup_data: True
  test_cfg:
    inference_on: teacher



metric: COCO
num_classes: 80

# partial labeled COCO, use `SemiCOCODataSet` rather than `COCODataSet`
TrainDataset:
  !SemiCOCODataSet
    image_dir: train2017
    anno_path: semi_annotations/instances_train2017.1@5.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
# partial unlabeled COCO, use `SemiCOCODataSet` rather than `COCODataSet`
UnsupTrainDataset:
  !SemiCOCODataSet
    image_dir: train2017
    anno_path: semi_annotations/instances_train2017.1@5-unlabeled.json
    dataset_dir: dataset/coco
    data_fields: ['image']
    supervised: False

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: dataset/coco
    allow_empty: true

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
    dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'

epoch: 180 #epoch: 60

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 1.0
    milestones: [180]
    use_warmup: true
  - !LinearWarmup
    start_factor: 0.001
    steps: 2000

OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001

#for labelmatch 
update_interval: 1000
LMReader:
  sample_transforms:
    - Decode: {}
    - Resize: { target_size: [640, 640], keep_ratio: False }
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1
  shuffle: true
  drop_last: false
  use_shared_memory: true
  collate_batch: true


TrainDatasetLM:
  !LMCocoDataset
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class']
    manual_length: 50
percent: 0.2
label_match: false